export const ACCOUNT_DATA = {
  balance: 45000,
  savings: 12000,
  totalReceived: 15500,
  totalSent: 8200,
  billsDue: 2500,
  transactions: [
    {
      id: 1,
      name: "Grocery Store",
      amount: 450,
      type: "sent",
      date: "Today",
      time: "2:30 PM",
      account: "ABC Supermarkets Ltd",
      accountNumber: "XXXX-XXXX-XXXX-1234",
      timestamp: "2024-11-04 14:30",
    },
    {
      id: 2,
      name: "Salary Credit",
      amount: 25000,
      type: "received",
      date: "Yesterday",
      time: "10:00 AM",
      account: "MyCompany HR Dept",
      accountNumber: "XXXX-XXXX-XXXX-5678",
      timestamp: "2024-11-03 10:00",
    },
    {
      id: 3,
      name: "Electricity Bill",
      amount: 1200,
      type: "sent",
      date: "2 days ago",
      time: "3:15 PM",
      account: "State Power Distribution",
      accountNumber: "XXXX-XXXX-XXXX-9012",
      timestamp: "2024-11-02 15:15",
    },
    {
      id: 4,
      name: "Freelance Payment",
      amount: 5000,
      type: "received",
      date: "3 days ago",
      time: "11:45 AM",
      account: "Digital Services Client",
      accountNumber: "XXXX-XXXX-XXXX-3456",
      timestamp: "2024-11-01 11:45",
    },
    {
      id: 5,
      name: "Restaurant",
      amount: 850,
      type: "sent",
      date: "4 days ago",
      time: "8:20 PM",
      account: "Food Delight Restaurant",
      accountNumber: "XXXX-XXXX-XXXX-7890",
      timestamp: "2024-10-31 20:20",
    },
  ],
}

export const TRANSACTIONS = ACCOUNT_DATA.transactions
